# Generated by Django 5.2 on 2025-04-20 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_favoritestock"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="favoritestock",
            unique_together={("user", "stock_symbol")},
        ),
    ]
